from app.schemas.common import APIResponse, MessageResponse, ErrorResponse
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    TokenPayload,
    UserProfileResponse,
)
from app.schemas.portal import (
    AnnouncementCreate,
    AnnouncementUpdate,
    AnnouncementResponse,
    AcademicCalendarCreate,
    AcademicCalendarResponse,
)
from app.schemas.admin import (
    AttendanceSummaryItem,
    AttendanceSummaryResponse,
    AttendanceTrendItem,
    FacultyActivityItem,
    FacultyAttendanceLogItem,
)
from app.schemas.faculty import (
    AttendanceRecordEntry,
    BatchAttendanceCreate,
    AttendanceUpdate,
    TimetableSlotResponse,
    AssignedCourseResponse,
    CourseAttendanceMetrics,
    StudentRosterItem,
    GradeEntry,
    BatchGradeCreate,
    GradeResponse,
    GradeUpdate,
    CourseMaterialCreate,
    CourseMaterialResponse,
)
from app.schemas.student import (
    StudentAttendanceItem,
    StudentAttendanceOverview,
    StudentAttendanceDetailItem,
    StudentTimetableSlot,
    StudentGradeItem,
    ProgressReport,
    StudentCourseItem,
)

__all__ = [
    "APIResponse",
    "MessageResponse",
    "ErrorResponse",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "TokenPayload",
    "UserProfileResponse",
    "AnnouncementCreate",
    "AnnouncementUpdate",
    "AnnouncementResponse",
    "AcademicCalendarCreate",
    "AcademicCalendarResponse",
    "AttendanceSummaryItem",
    "AttendanceSummaryResponse",
    "AttendanceTrendItem",
    "FacultyActivityItem",
    "FacultyAttendanceLogItem",
    "AttendanceRecordEntry",
    "BatchAttendanceCreate",
    "AttendanceUpdate",
    "TimetableSlotResponse",
    "AssignedCourseResponse",
    "CourseAttendanceMetrics",
    "StudentRosterItem",
    "GradeEntry",
    "BatchGradeCreate",
    "GradeResponse",
    "GradeUpdate",
    "CourseMaterialCreate",
    "CourseMaterialResponse",
    "StudentAttendanceItem",
    "StudentAttendanceOverview",
    "StudentAttendanceDetailItem",
    "StudentTimetableSlot",
    "StudentGradeItem",
    "ProgressReport",
    "StudentCourseItem",
]
